### PR TITLE
Support mtl 2.3

### PR DESCRIPTION
**Pull request by sjakobi**
https://hackage.haskell.org/package/mtl-2.3/changelog

### CODE REVIEW

**Comment by sjakobi** [comment]
Ping @sdiehl! :)

**Comment by adamwespiser** [comment]
I'm the maintainer now, and will be able to merge this shortly.
However, I need to add a gitlab CI script and replace the travis script. Otherwise, we have no build coverage and risk pushing broken code.

**Comment by sjakobi** [comment]
Hi Adam! I'm happy to hear that this library has an active maintainer again! :)

Regarding CI – in case you meant a CI script for GitHub, I can recommend https://github.com/haskell-CI/haskell-ci#readme. I've used it a lot, so in case you have any questions, please let me know! :)

**Comment by adamwespiser** [comment]
Can you rebase on this? https://github.com/sdiehl/repline/pull/41 it's merged in, and should be on `master` by the time you read this :)

**Pull request merged**
